name: hatonet_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  snippet_coder_utils: ^1.0.12
  fa_stepper: ^0.0.2
  email_validator: ^2.0.1
  wc_form_validators: ^1.0.0

  flutter_slidable: ^2.0.0
  # shimmer
  shimmer: ^2.0.0

  # drawer
  flutter_slider_drawer: ^2.1.1
  # app icon
  flutter_launcher_icons: ^0.11.0

  # For Architecture
  provider: ^6.0.1

  #Dependency Injection
  get_it: ^7.2.0
  get: ^4.3.8

  #For Networking
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.0
  #For large log
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  #Lazy Json Serialization
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0

  # Reactive Programming
  rxdart: ^0.27.4
  #event bus
  event_bus: ^2.0.0

  #For UI
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  flutter_svg: ^1.1.6
  bouncing_widget: ^2.0.0
  roundcheckbox: ^2.0.4
  flutter_staggered_grid_view: ^0.6.1
  expandable: ^5.0.1
  custom_radio_grouped_button: ^2.1.2
  #multi adapting screen and font size
  flutter_screenutil: ^5.0.0+2
  intl: ^0.17.0
  #format date time for parsing
  jiffy: ^5.0.0
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.4
  webview_flutter: ^3.0.4
  transparent_image: ^2.0.0

  # For Google and Firebase
  #control notification in android & ios
  flutter_local_notifications: ^12.0.3+1

  #For Local Storage
  shared_preferences: ^2.0.15

  # Package Info
  device_info_plus: ^8.0.0
  package_info: ^2.0.2

  #For Permission
  permission_handler: ^10.2.0

  #File path
  path_provider: ^2.0.1

  #For access local image
  image_picker: ^0.8.4+10

  #For File Picker:
  file_picker: ^5.2.2

  #launch browser
  url_launcher: ^6.0.18

  #format string
  sprintf: ^6.0.0

  # save widget as image
  screenshot: ^1.2.3

  #Share to SNS
  share: ^2.0.4

  #Flutter Flavors Dev & Prod
  flutter_flavorizr: ^2.1.3

  #multiple language
  easy_localization: ^3.0.1

  persistent_bottom_nav_bar: ^4.0.2

  smooth_page_indicator: ^1.0.0+2
  percent_indicator: ^4.2.2

  firebase_auth: ^4.1.3

  http: ^0.13.3

  cloud_firestore: ^4.1.0

  google_fonts: ^3.0.1
  google_sign_in: ^5.4.1

  flutter_scale_tap:
    git: https://github.com/magicpro97/flutter_scale_tap
  font_awesome_flutter: ^10.1.0
  firebase_core: ^2.3.0

  dropdown_button2: ^1.7.2
  dropdown_textfield: ^1.0.3

  auto_size_text: ^3.0.0



  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.3

  rounded_loading_button: ^2.1.0
  connectivity_plus: ^2.3.6+1
  flutter_facebook_auth: ^5.0.6


  material_dialogs: ^1.1.3

  lottie: ^1.4.2
  grpc: ^3.0.2
  protobuf: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #auto gen
  build_runner:
  flutter_lints: ^2.0.1

#ICON LAUNCHER
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/lo.png"


#Flavor Dev & Prod
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "Business Suite Pos(dev)"
      android:
        applicationId: "com.businesssuite.business_suite_mobile_pos"
      ios:
        bundleId: "com.businesssuite.business_suite_mobile_pos"

    production:
      app:
        name: "Business Suite Pos"
      android:
        applicationId: "com.businesssuite.business_suite_mobile_pos"
      ios:
        bundleId: "com.businesssuite.business_suite_mobile_pos"


flutter:
  uses-material-design: true

  # res icon, image, sound...
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/animations/
    - assets/animations/onboarding/
    - assets/animations/onboarding/images/